---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversionmicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversionmicroservice
  template:
    metadata:
      labels:
        app: conversionmicroservice
    spec:
      containers:
      - name: conversionmicroservice
        image: mpresecki/conversionmicroserviceapi:mycookbook_v1
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
---
apiVersion: v1
kind: Service
metadata:
  name: conversionmicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: conversionmicroservice
