---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealmicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealmicroservice
  template:
    metadata:
      labels:
        app: mealmicroservice
    spec:
      containers:
      - name: mealmicroservice
        image: mpresecki/mealmicroserviceapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: DB_PW
          value: User1234
        - name: AppSettings__RecipeAPI
          value: http://51.105.207.19/api/Recipe
---
apiVersion: v1
kind: Service
metadata:
  name: mealmicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mealmicroservice
