---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermicroservice
  template:
    metadata:
      labels:
        app: usermicroservice
    spec:
      containers:
      - name: usermicroservice
        image: mpresecki/usermicroserviceapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: DB_PW
          value: User1234
---
apiVersion: v1
kind: Service
metadata:
  name: usermicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: usermicroservice
